### ISSUE TITLE
ChromeDriver laden

### ISSUE THREAD

**Issue by VincentVelthuizen** [Daniel-Kuperus/Plannie#1]
Kun je hier iets mee?

https://stackoverflow.com/questions/50566186/can-we-add-drivers-in-selenium-as-maven-depandancies/50587347#50587347

https://stackoverflow.com/questions/54599169/how-to-configure-selenium-webdriver-with-spring-boot-for-ui-testing

**Comment by Daniel-Kuperus** [comment]
Dankjewel!, ik zal nog wel even moeten kijken hoe we die van ons het beste kunnen implementeren.
